#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=40gb
#SBATCH -t 12:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=qiuxx221@umn.edu
#SBATCH -o unmapped_xaa.out
#SBATCH -e unmapped_xaa.err
#SBATCH --tmp=300gb

cd /home/hirschc1/qiuxx221/widiv/de_novo/split_folder_509/bams

module load samtools

for i in *B73v5.bam; do 
  samtools view -f4 $i > $i.unmapped.sam
  rm $i
done 

for j in *.unmapped.sam; do 
  echo $j; 
  cat $j | grep -v ^@  | awk 'NR%2==1 {print "@"$1"\n"$10"\n+\n"$11}' > "$j"_1.fastq 
  cat $j | grep -v ^@  | awk 'NR%2==0 {print "@"$1"\n"$10"\n+\n"$11}' > "$j"_2.fastq
  rm $j
done 
