#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=10gb
#SBATCH -t 10:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=qiuxx221@umn.edu
#SBATCH -o extract_unmapped_reads.out
#SBATCH -e extract_unmapped_reads.err
#SBATCH --tmp=100gb

cd /home/hirschc1/qiuxx221/widiv/unmapped_only

module load samtools

for i in *B73v5.bam; do 
  samtools view -f4 $i > $i.unmapped.sam
done 

for j in *.unmapped.sam; do 
  echo $j; 
  cat $j | grep -v ^@  | awk 'NR%2==1 {print "@"$1"\n"$10"\n+\n"$11}' > "$j"_1.fastq 
  cat $j | grep -v ^@  | awk 'NR%2==0 {print "@"$1"\n"$10"\n+\n"$11}' > "$j"_2.fastq
done 
