#!/bin/bash
#SBATCH -N 1
#SBATCH -n 8
#SBATCH -t 80:00:00
#SBATCH --mem=200gb
#SBATCH --tmp=300gb
#SBATCH -J LH82
#SBATCH -o LH82.o%j
#SBATCH -e LH82.e%j
#SBATCH --mail-user=qiuxx221@umn.edu
#SBATCH --mail-type=ALL
export PATH="/home/hirschc1/qiuxx221/anaconda2/bin/:$PATH"
source ~/anaconda2/etc/profile.d/conda.sh
conda activate Widiv_SV_py3
module load bcftools

cd /scratch.global/qiuxx221/bam_picard_xac/picard_xac_bam

delly call -o LH82_B73v5_marked_duplicates.bam.delly.bcf -g /panfs/roc/groups/6/maize/shared/databases/genomes/Zea_mays/B73_NAMassembly/Zm-B73-REFERENCE-NAM-5.0/Zm-B73-REFERENCE-NAM-5.0.fasta LH82_B73v5_marked_duplicates.bam; bcftools view LH82_B73v5_marked_duplicates.bam.delly.bcf > LH82_B73v5_marked_duplicates.bam.delly.vcf

