#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=30gb
#SBATCH -t 10:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=qiuxx221@umn.edu
#SBATCH -o annotate_751e5.out
#SBATCH -e annotate_751e5.err

cd ~/widiv/de_novo/de_novo_unmap_sam/fastq/509_assembly/kmer53_509/pan_contigs_annotation/masked

export PATH="/home/hirschc1/qiuxx221/anaconda2/bin/:$PATH"

source ~/anaconda2/etc/profile.d/conda.sh
conda activate Widiv_SV_py3

augustus --species=maize --strand=both top5_uniq_plant_contigs_id1e5_short_header.fasta.masked --gff3=on > top5_uniq_plant_contigs_id1e5_short_header.fasta.masked_annotation.gff3
