#!/bin/bash
#SBATCH --partition=amdsmall,ram1t,amd512
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=20
#SBATCH --mem=100gb
#SBATCH -t 96:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=qiuxx221@umn.edu
#SBATCH -o blastn_contigs_back_ref.out
#SBATCH -e blastn_contigs_back_ref.err
#SBATCH --tmp=100gb

cd ~/widiv/de_novo/de_novo_unmap_sam/fastq/509_assembly/kmer53_509/pan_contigs_annotation/blast_ref

module load parallel/20190122
module load ncbi_toolkits

parallel --tmpdir /home/hirschc1/qiuxx221/temp/ --jobs 19 < blast_to_ref_list_fa_cmd 

blastn -db ~/widiv/B73_index/Zm-B73-REFERENCE-NAM-5.0.fasta -query contigs_for_blast100000.fa -perc_identity 75 -max_target_seqs 1 -outfmt "7 qseqid sseqid slen qstart qend length mismatch gapopen gaps sseq qcovs" -out /scratch.global/qiuxx221/contigs_for_blast100000.fa_blast_to_ref75_qcov.out 


