#!/bin/bash
#SBATCH --partition=amdsmall,ram1t,amd512
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=20
#SBATCH --mem=100gb
#SBATCH -t 96:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=qiuxx221@umn.edu
#SBATCH -o blastn_contigs_back_ref.out
#SBATCH -e blastn_contigs_back_ref.err
#SBATCH --tmp=100gb

cd ~/widiv/de_novo/de_novo_unmap_sam/fastq/509_assembly/kmer53_509/pan_contigs_annotation/blast_ref

module load parallel/20190122
module load ncbi_toolkits

parallel --tmpdir /home/hirschc1/qiuxx221/temp/ --jobs 19 < blast_to_ref_list_fa_cmd 

